force-app/main/default/objects/AccountSettings__c/AccountSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings for Account</description>
    <label>Account Settings</label>
</CustomObject>

force-app/main/default/objects/AccountSettings__c/fields/TRG_CalculateTotalAmountForTheCustomer__c.field-meta.xml
<CustomField>
    <fullName>TRG_CalculateTotalAmountForTheCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to switch on the calculation of weighted loan amount for the customer.</description>
    <label>TRG_CalculateTotalAmountForTheCustomer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application object to record applications for loans.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LoanAmount__c.field-meta.xml
<CustomField>
    <fullName>LoanAmount__c</fullName>
    <description>Total Loan Amount</description>
    <label>Loan Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApplicationTriggerHandler.cls
public class ApplicationTriggerHandler extends TriggerHandler {
    private Map<Id, Application__c> newApplicationMap;
    private Map<Id, Application__c> oldApplicationMap;

    private List<Application__c> newApplicationList;
    private List<Application__c> oldApplicationList;

    public ApplicationTriggerHandler() {
        this.newApplicationList = (List<Application__c>) Trigger.new;
        this.oldApplicationList = (List<Application__c>) Trigger.old; 
        this.newApplicationMap  = (Map<Id, Application__c>) Trigger.newMap;
        this.oldApplicationMap  = (Map<Id, Application__c>) Trigger.oldMap;
    }

    public override void afterInsert() {
        if(AccountSettings__c.getInstance().TRG_CalculateTotalAmountForTheCustomer__c) {
            List<String> applicationIdList = new List<String>();

            for(Application__c application : newApplicationList) {
                applicationIdList.add(application.Id);
            }
            LoanAmountCalculationService.calculateTotalAmountForApplicationIds(applicationIdList);
        }
    }

    public override void afterUpdate() {
        if(AccountSettings__c.getInstance().TRG_CalculateTotalAmountForTheCustomer__c) {
            List<String> applicationIdList = new List<String>();

            for(Application__c application : newApplicationList) {
                Application__c oldRecord = oldApplicationMap.get(application.Id);
                if (application.LoanAmount__c != oldRecord.LoanAmount__c) {
                    applicationIdList.add(application.Id);
                }
            }
            LoanAmountCalculationService.calculateTotalAmountForApplicationIds(applicationIdList);
        }
    }

    public override void beforeDelete() {
        if(AccountSettings__c.getInstance().TRG_CalculateTotalAmountForTheCustomer__c) {
            List<String> applicationIdList = new List<String>();

            for(Application__c application : oldApplicationList) {
                applicationIdList.add(application.Id);
            }
            LoanAmountCalculationService.calculateTotalAmountForDeletedApplications(applicationIdList);
        }
    }

}