force-app/main/default/objects/AccountSettings__c/AccountSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings for Account</description>
    <label>Account Settings</label>
</CustomObject>

force-app/main/default/objects/AccountSettings__c/fields/TRG_CalculateTotalAmountForTheCustomer__c.field-meta.xml
<CustomField>
    <fullName>TRG_CalculateTotalAmountForTheCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to switch on the calculation of weighted loan amount for the customer.</description>
    <label>TRG_CalculateTotalAmountForTheCustomer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>Each customer (Account) applying for the loan application will have an Applicant record.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Master Application for the applicant</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/ApplicationOwnership__c.field-meta.xml
<CustomField>
    <fullName>ApplicationOwnership__c</fullName>
    <description>Percentage ownership of the application.</description>
    <label>Application Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application object to record applications for loans.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApplicantTriggerHandler.cls
public class ApplicantTriggerHandler extends TriggerHandler {
    private Map<Id, Applicant__c> newApplicantMap;
    private Map<Id, Applicant__c> oldApplicantMap;

    private List<Applicant__c> newApplicantList;
    private List<Applicant__c> oldApplicantList;

    public ApplicantTriggerHandler() {
        this.newApplicantList = (List<Applicant__c>) Trigger.new;
        this.oldApplicantList = (List<Applicant__c>) Trigger.old; 
        this.newApplicantMap  = (Map<Id, Applicant__c>) Trigger.newMap;
        this.oldApplicantMap  = (Map<Id, Applicant__c>) Trigger.oldMap;
    }

    public override void afterInsert() {
        if(AccountSettings__c.getInstance().TRG_CalculateTotalAmountForTheCustomer__c) {
            List<String> accountIdList = new List<String>();

            for(Applicant__c applicant : newApplicantList) {
                if (applicant.Account__c != null) { accountIdList.add(applicant.Account__c); }
            }
            LoanAmountCalculationService.calculateTotalAmountForAccountIds(accountIdList);
        }
    }

    public override void afterUpdate() {
        if(AccountSettings__c.getInstance().TRG_CalculateTotalAmountForTheCustomer__c) {
            List<String> accountIdList = new List<String>();

            for(Applicant__c applicant : newApplicantList) {
                Applicant__c oldRecord = oldApplicantMap.get(applicant.Id);
                if (applicant.ApplicationOwnership__c != oldRecord.ApplicationOwnership__c ||
                    applicant.Application__c != oldRecord.Application__c) {
                        accountIdList.add(applicant.Account__c);
                }
                if (applicant.Account__c != oldRecord.Account__c) {
                    if (applicant.Account__c != null) { accountIdList.add(applicant.Account__c); }
                    if (oldRecord.Account__c != null) { accountIdList.add(oldRecord.Account__c); }
                }
            }
            LoanAmountCalculationService.calculateTotalAmountForAccountIds(accountIdList);
        }
    }

    public override void afterDelete() {
        if(AccountSettings__c.getInstance().TRG_CalculateTotalAmountForTheCustomer__c) {
            List<String> accountIdList = new List<String>();

            for(Applicant__c applicant : oldApplicantList) {
                if (applicant.Account__c != null) { accountIdList.add(applicant.Account__c); }
            }
            LoanAmountCalculationService.calculateTotalAmountForAccountIds(accountIdList);
        }
    }
}