force-app/main/default/objects/Account/fields/TotalLoanAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalLoanAmount__c</fullName>
    <description>Total of all the applications&apos; loan amount weighted with ownership of the customer.</description>
    <label>Total Loan Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>Each customer (Account) applying for the loan application will have an Applicant record.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Master Application for the applicant</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/ApplicationOwnership__c.field-meta.xml
<CustomField>
    <fullName>ApplicationOwnership__c</fullName>
    <description>Percentage ownership of the application.</description>
    <label>Application Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application object to record applications for loans.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LoanAmount__c.field-meta.xml
<CustomField>
    <fullName>LoanAmount__c</fullName>
    <description>Total Loan Amount</description>
    <label>Loan Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoanAmountCalculationService.cls
public class LoanAmountCalculationService {
    
    public static void calculateTotalAmountForAccountIds(List<String> accountIdList) {
        List<Applicant__c> applicantList = [
            SELECT Id, Name, Account__c, Application__r.LoanAmount__c, ApplicationOwnership__c 
            FROM Applicant__c WHERE Account__c IN :accountIdList
        ];

        calculateTotalAmountForApplicant(applicantList, accountIdList);  
    }

    public static void calculateTotalAmountForApplicationIds(List<String> applicationIdList) {
        List<Applicant__c> applicantList = [ 
            SELECT Id, Name, Account__c FROM Applicant__c WHERE Application__c IN :applicationIdList 
        ];
        List<String> accountIdList = new List<String>();

        System.debug('applicantList : ' + applicantList);
        
        for (Applicant__c applicant : applicantList) {
            accountIdList.add(applicant.Account__c);
        }

        calculateTotalAmountForAccountIds(accountIdList);  
    }

    public static void calculateTotalAmountForDeletedApplications(List<String> applicationIdList) {
        List<Applicant__c> applicantListForDeletedApps = [ 
            SELECT Id, Name, Account__c FROM Applicant__c WHERE Application__c IN :applicationIdList 
        ];
        List<String> accountIdList = new List<String>();

        for (Applicant__c applicant : applicantListForDeletedApps) {
            accountIdList.add(applicant.Account__c);
        }

        List<Applicant__c> applicantList = [
            SELECT Id, Name, Account__c, Application__r.LoanAmount__c, ApplicationOwnership__c 
            FROM Applicant__c 
            WHERE Account__c IN :accountIdList
            AND Application__c NOT IN :applicationIdList
        ];

        calculateTotalAmountForApplicant(applicantList, accountIdList);  
    }

    private static void calculateTotalAmountForApplicant(List<Applicant__c> applicantList, List<String> accountIdList) {
        Map<String, Decimal> accountIdToTotalLoanMap = new Map<String, Decimal>();

        for (Applicant__c applicant : applicantList) {
            if (accountIdToTotalLoanMap.containsKey(applicant.Account__c) == false) {
                accountIdToTotalLoanMap.put(applicant.Account__c, 0.0);
            }
            accountIdToTotalLoanMap.put(applicant.Account__c, 
                    accountIdToTotalLoanMap.get(applicant.Account__c) + 
                    applicant.ApplicationOwnership__c/100 * applicant.Application__r.LoanAmount__c);
        }

        for (String accountId : accountIdList) {
            if (accountIdToTotalLoanMap.containsKey(accountId) == false) {      // to handle cases where all applicant
                accountIdToTotalLoanMap.put(accountId, 0.0);                    //records are deleted for the account
            }
        }
        List<Account> updatedAccountList = new List<Account>();

        for (String accountId : accountIdToTotalLoanMap.keySet()) {
            updatedAccountList.add(new Account(Id = accountId, TotalLoanAmount__c = accountIdToTotalLoanMap.get(accountId)));
        }

        if(updatedAccountList.size() > 0) { update updatedAccountList; }
    }
}