force-app/main/default/objects/Account/fields/TotalLoanAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalLoanAmount__c</fullName>
    <description>Total of all the applications&apos; loan amount weighted with ownership of the customer.</description>
    <label>Total Loan Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AccountSettings__c/AccountSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings for Account</description>
    <label>Account Settings</label>
</CustomObject>

force-app/main/default/objects/AccountSettings__c/fields/TRG_CalculateTotalAmountForTheCustomer__c.field-meta.xml
<CustomField>
    <fullName>TRG_CalculateTotalAmountForTheCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to switch on the calculation of weighted loan amount for the customer.</description>
    <label>TRG_CalculateTotalAmountForTheCustomer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <description>Each customer (Account) applying for the loan application will have an Applicant record.</description>
    <label>Applicant</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Master Application for the applicant</description>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Applicants</relationshipLabel>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/ApplicationOwnership__c.field-meta.xml
<CustomField>
    <fullName>ApplicationOwnership__c</fullName>
    <description>Percentage ownership of the application.</description>
    <label>Application Ownership</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>Application object to record applications for loans.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/LoanAmount__c.field-meta.xml
<CustomField>
    <fullName>LoanAmount__c</fullName>
    <description>Total Loan Amount</description>
    <label>Loan Amount</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoanAmountCalculationServiceTest.cls
@IsTest
public class LoanAmountCalculationServiceTest {
    @TestSetup
    static void setup(){
        AccountSettings__c accountSettings = new AccountSettings__c();
        accountSettings.TRG_CalculateTotalAmountForTheCustomer__c = true;

        insert accountSettings;

        List<Account> accountList = new List<Account>();

        Account account1 = new Account(Name='Account1');
        accountList.add(account1);

        Account account2 = new Account(Name='Account2');
        accountList.add(account2);

        insert accountList;

        Application__c application  = new Application__c(LoanAmount__c = 10000);

        insert application;
    }

    @IsTest
    static void testLoanAmountCalculationOnApplicantInsert(){
        Account account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        
        System.assertNotEquals(5000, account.TotalLoanAmount__c);
        Application__c application  = [SELECT Id, Name FROM Application__c LIMIT 1 ];

        Applicant__c applicant = new Applicant__c( Account__c               = account.Id, 
                                                   Application__c           = application.Id,
                                                   ApplicationOwnership__c  = 50);

        Test.startTest();
        insert applicant;
        Test.stopTest();

        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        
        System.assertEquals(5000, account.TotalLoanAmount__c);
    }

    @IsTest
    static void testLoanAmountCalculationOnApplicantUpdate(){
        Account account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        
        System.assertNotEquals(5000, account.TotalLoanAmount__c);
        Application__c application  = [SELECT Id, Name FROM Application__c LIMIT 1 ];

        Applicant__c applicant = new Applicant__c( Account__c               = account.Id, 
                                                   Application__c           = application.Id,
                                                   ApplicationOwnership__c  = 50);

        
        insert applicant;

        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        
        System.assertEquals(5000, account.TotalLoanAmount__c);

        Test.startTest();

        applicant.ApplicationOwnership__c = 75;
        update applicant;
        Test.stopTest();

        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        System.assertEquals(7500, account.TotalLoanAmount__c);

        applicant.Account__c = null;
        update applicant;

        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        System.assertEquals(0, account.TotalLoanAmount__c);
    
        delete applicant;

        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        System.assertEquals(0, account.TotalLoanAmount__c);
    }

    @IsTest
    static void testLoanAmountCalculationOnApplication(){
        Account account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        
        System.assertNotEquals(5000, account.TotalLoanAmount__c);
        Application__c application  = [SELECT Id, Name FROM Application__c LIMIT 1 ];

        Applicant__c applicant = new Applicant__c( Account__c               = account.Id, 
                                                   Application__c           = application.Id,
                                                   ApplicationOwnership__c  = 50);
        insert applicant;
        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        System.assertEquals(5000, account.TotalLoanAmount__c);

        Application__c application2  = new Application__c(LoanAmount__c = 10000);
        insert application2;

        Applicant__c applicant2 = new Applicant__c( Account__c              = account.Id, 
                                                   Application__c           = application2.Id,
                                                   ApplicationOwnership__c  = 20);
        insert applicant2;

        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        System.assertEquals(7000, account.TotalLoanAmount__c);

        application2.LoanAmount__c = 20000;
        update application2;

        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        System.assertEquals(9000, account.TotalLoanAmount__c);

        delete application2;
        account = [ SELECT Id, Name, TotalLoanAmount__c FROM Account LIMIT 1 ];
        System.assertEquals(5000, account.TotalLoanAmount__c);
    }
}